# Generated by Django 3.2.1 on 2023-12-18 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DishManagement',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='菜品名称')),
                ('Dishclass', models.CharField(max_length=100, verbose_name='菜品种类')),
                ('image', models.CharField(max_length=100, verbose_name='图片')),
                ('inventory', models.IntegerField(default=0, verbose_name='库存')),
                ('price', models.IntegerField(default=0, verbose_name='价格')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '菜品管理',
                'verbose_name_plural': '菜品管理',
            },
        ),
        migrations.AlterModelOptions(
            name='dishcategory',
            options={'verbose_name': '菜品种类', 'verbose_name_plural': '菜品种类'},
        ),
    ]
