# Generated by Django 3.2.1 on 2023-12-18 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20231218_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishmanagement',
            name='Dishclass',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pk_Dishclass', to='order.dishcategory', verbose_name='菜品种类'),
        ),
    ]
