# Generated by Django 3.2.1 on 2023-12-19 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_dishmanagement_dishimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishmanagement',
            name='pacakge',
            field=models.FileField(blank=True, null=True, upload_to='test/uploads/', verbose_name='其他压缩包'),
        ),
    ]
