# Generated by Django 3.2.1 on 2023-12-19 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_dishmanagement_pacakge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dishmanagement',
            name='pacakge',
        ),
        migrations.AddField(
            model_name='dishmanagement',
            name='DishCategoryList',
            field=models.ManyToManyField(to='order.DishCategory'),
        ),
    ]
