# Generated by Django 3.2.1 on 2023-12-19 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20231219_0953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dishmanagement',
            name='DishCategoryList',
        ),
    ]
