# Generated by Django 3.2.1 on 2023-12-19 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_remove_dishmanagement_dishcategorylist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dishmanagement',
            name='Dishimage',
        ),
    ]
