# Generated by Django 3.2.1 on 2023-12-19 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_dishmanagement_dishimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dishmanagement',
            name='Dishimage',
        ),
    ]
