# Generated by Django 3.2.1 on 2023-12-19 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_remove_dishmanagement_dishimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishcategory',
            name='type',
            field=models.CharField(default='', max_length=100, verbose_name='type'),
        ),
    ]
