# Generated by Django 3.2.1 on 2023-12-19 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_dishmanagement_dishimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='test')),
            ],
        ),
    ]
